// Capitals + a curated set of major cities, grouped loosely by continent.
// continent labels are Dutch, used for grouping the sidebar list.
export const CITIES = [

/* ---------------- Europa ---------------- */
{name:'Tirana', country:'Albania', lat:41.33, lng:19.82, capital:true, continent:'Europa'},
{name:'Andorra la Vella', country:'Andorra', lat:42.51, lng:1.52, capital:true, continent:'Europa'},
{name:'Vienna', country:'Austria', lat:48.21, lng:16.37, capital:true, continent:'Europa'},
{name:'Minsk', country:'Belarus', lat:53.9, lng:27.57, capital:true, continent:'Europa'},
{name:'Brussels', country:'Belgium', lat:50.85, lng:4.35, capital:true, continent:'Europa'},
{name:'Sarajevo', country:'Bosnia and Herzegovina', lat:43.86, lng:18.41, capital:true, continent:'Europa'},
{name:'Sofia', country:'Bulgaria', lat:42.7, lng:23.32, capital:true, continent:'Europa'},
{name:'Zagreb', country:'Croatia', lat:45.81, lng:15.98, capital:true, continent:'Europa'},
{name:'Nicosia', country:'Cyprus', lat:35.19, lng:33.38, capital:true, continent:'Europa'},
{name:'Prague', country:'Czechia', lat:50.08, lng:14.44, capital:true, continent:'Europa'},
{name:'Copenhagen', country:'Denmark', lat:55.68, lng:12.57, capital:true, continent:'Europa'},
{name:'Tallinn', country:'Estonia', lat:59.44, lng:24.75, capital:true, continent:'Europa'},
{name:'Helsinki', country:'Finland', lat:60.17, lng:24.94, capital:true, continent:'Europa'},
{name:'Paris', country:'France', lat:48.86, lng:2.35, capital:true, continent:'Europa'},
{name:'Marseille', country:'France', lat:43.3, lng:5.37, capital:false, continent:'Europa'},
{name:'Berlin', country:'Germany', lat:52.52, lng:13.41, capital:true, continent:'Europa'},
{name:'Munich', country:'Germany', lat:48.14, lng:11.58, capital:false, continent:'Europa'},
{name:'Hamburg', country:'Germany', lat:53.55, lng:9.99, capital:false, continent:'Europa'},
{name:'Athens', country:'Greece', lat:37.98, lng:23.73, capital:true, continent:'Europa'},
{name:'Budapest', country:'Hungary', lat:47.5, lng:19.04, capital:true, continent:'Europa'},
{name:'Reykjavik', country:'Iceland', lat:64.15, lng:-21.94, capital:true, continent:'Europa'},
{name:'Dublin', country:'Ireland', lat:53.35, lng:-6.26, capital:true, continent:'Europa'},
{name:'Rome', country:'Italy', lat:41.9, lng:12.5, capital:true, continent:'Europa'},
{name:'Milan', country:'Italy', lat:45.46, lng:9.19, capital:false, continent:'Europa'},
{name:'Pristina', country:'Kosovo', lat:42.67, lng:21.17, capital:true, continent:'Europa'},
{name:'Riga', country:'Latvia', lat:56.95, lng:24.11, capital:true, continent:'Europa'},
{name:'Vaduz', country:'Liechtenstein', lat:47.14, lng:9.52, capital:true, continent:'Europa'},
{name:'Vilnius', country:'Lithuania', lat:54.69, lng:25.28, capital:true, continent:'Europa'},
{name:'Luxembourg', country:'Luxembourg', lat:49.61, lng:6.13, capital:true, continent:'Europa'},
{name:'Valletta', country:'Malta', lat:35.9, lng:14.51, capital:true, continent:'Europa'},
{name:'Chisinau', country:'Moldova', lat:47.01, lng:28.86, capital:true, continent:'Europa'},
{name:'Monaco', country:'Monaco', lat:43.73, lng:7.42, capital:true, continent:'Europa'},
{name:'Podgorica', country:'Montenegro', lat:42.44, lng:19.26, capital:true, continent:'Europa'},
{name:'Amsterdam', country:'Netherlands', lat:52.37, lng:4.9, capital:true, continent:'Europa'},
{name:'Skopje', country:'North Macedonia', lat:42.0, lng:21.43, capital:true, continent:'Europa'},
{name:'Oslo', country:'Norway', lat:59.91, lng:10.75, capital:true, continent:'Europa'},
{name:'Warsaw', country:'Poland', lat:52.23, lng:21.01, capital:true, continent:'Europa'},
{name:'Lisbon', country:'Portugal', lat:38.72, lng:-9.14, capital:true, continent:'Europa'},
{name:'Bucharest', country:'Romania', lat:44.43, lng:26.1, capital:true, continent:'Europa'},
{name:'Moscow', country:'Russia', lat:55.76, lng:37.62, capital:true, continent:'Europa'},
{name:'Saint Petersburg', country:'Russia', lat:59.93, lng:30.34, capital:false, continent:'Europa'},
{name:'San Marino', country:'San Marino', lat:43.94, lng:12.45, capital:true, continent:'Europa'},
{name:'Belgrade', country:'Serbia', lat:44.79, lng:20.45, capital:true, continent:'Europa'},
{name:'Bratislava', country:'Slovakia', lat:48.15, lng:17.11, capital:true, continent:'Europa'},
{name:'Ljubljana', country:'Slovenia', lat:46.06, lng:14.5, capital:true, continent:'Europa'},
{name:'Madrid', country:'Spain', lat:40.42, lng:-3.7, capital:true, continent:'Europa'},
{name:'Barcelona', country:'Spain', lat:41.39, lng:2.16, capital:false, continent:'Europa'},
{name:'Stockholm', country:'Sweden', lat:59.33, lng:18.06, capital:true, continent:'Europa'},
{name:'Bern', country:'Switzerland', lat:46.95, lng:7.44, capital:true, continent:'Europa'},
{name:'Kyiv', country:'Ukraine', lat:50.45, lng:30.52, capital:true, continent:'Europa'},
{name:'London', country:'United Kingdom', lat:51.51, lng:-0.13, capital:true, continent:'Europa'},
{name:'Manchester', country:'United Kingdom', lat:53.48, lng:-2.24, capital:false, continent:'Europa'},
{name:'Vatican City', country:'Vatican', lat:41.9, lng:12.45, capital:true, continent:'Europa'},

/* ---------------- Azië ---------------- */
{name:'Kabul', country:'Afghanistan', lat:34.53, lng:69.17, capital:true, continent:'Azië'},
{name:'Yerevan', country:'Armenia', lat:40.18, lng:44.51, capital:true, continent:'Azië'},
{name:'Baku', country:'Azerbaijan', lat:40.41, lng:49.87, capital:true, continent:'Azië'},
{name:'Manama', country:'Bahrain', lat:26.23, lng:50.59, capital:true, continent:'Azië'},
{name:'Dhaka', country:'Bangladesh', lat:23.81, lng:90.41, capital:true, continent:'Azië'},
{name:'Thimphu', country:'Bhutan', lat:27.47, lng:89.64, capital:true, continent:'Azië'},
{name:'Bandar Seri Begawan', country:'Brunei', lat:4.94, lng:114.94, capital:true, continent:'Azië'},
{name:'Phnom Penh', country:'Cambodia', lat:11.56, lng:104.92, capital:true, continent:'Azië'},
{name:'Beijing', country:'China', lat:39.9, lng:116.41, capital:true, continent:'Azië'},
{name:'Shanghai', country:'China', lat:31.23, lng:121.47, capital:false, continent:'Azië'},
{name:'Hong Kong', country:'China', lat:22.32, lng:114.17, capital:false, continent:'Azië'},
{name:'Tbilisi', country:'Georgia', lat:41.72, lng:44.79, capital:true, continent:'Azië'},
{name:'New Delhi', country:'India', lat:28.61, lng:77.21, capital:true, continent:'Azië'},
{name:'Mumbai', country:'India', lat:19.08, lng:72.88, capital:false, continent:'Azië'},
{name:'Jakarta', country:'Indonesia', lat:-6.21, lng:106.85, capital:true, continent:'Azië'},
{name:'Surabaya', country:'Indonesia', lat:-7.25, lng:112.75, capital:false, continent:'Azië'},
{name:'Tehran', country:'Iran', lat:35.69, lng:51.39, capital:true, continent:'Azië'},
{name:'Baghdad', country:'Iraq', lat:33.31, lng:44.36, capital:true, continent:'Azië'},
{name:'Jerusalem', country:'Israel', lat:31.77, lng:35.21, capital:true, continent:'Azië'},
{name:'Tel Aviv', country:'Israel', lat:32.08, lng:34.78, capital:false, continent:'Azië'},
{name:'Tokyo', country:'Japan', lat:35.68, lng:139.69, capital:true, continent:'Azië'},
{name:'Osaka', country:'Japan', lat:34.69, lng:135.5, capital:false, continent:'Azië'},
{name:'Amman', country:'Jordan', lat:31.95, lng:35.93, capital:true, continent:'Azië'},
{name:'Astana', country:'Kazakhstan', lat:51.16, lng:71.47, capital:true, continent:'Azië'},
{name:'Almaty', country:'Kazakhstan', lat:43.24, lng:76.9, capital:false, continent:'Azië'},
{name:'Kuwait City', country:'Kuwait', lat:29.38, lng:47.98, capital:true, continent:'Azië'},
{name:'Bishkek', country:'Kyrgyzstan', lat:42.87, lng:74.59, capital:true, continent:'Azië'},
{name:'Vientiane', country:'Laos', lat:17.97, lng:102.6, capital:true, continent:'Azië'},
{name:'Beirut', country:'Lebanon', lat:33.89, lng:35.5, capital:true, continent:'Azië'},
{name:'Kuala Lumpur', country:'Malaysia', lat:3.14, lng:101.69, capital:true, continent:'Azië'},
{name:'Malé', country:'Maldives', lat:4.17, lng:73.51, capital:true, continent:'Azië'},
{name:'Ulaanbaatar', country:'Mongolia', lat:47.89, lng:106.91, capital:true, continent:'Azië'},
{name:'Naypyidaw', country:'Myanmar', lat:19.75, lng:96.13, capital:true, continent:'Azië'},
{name:'Yangon', country:'Myanmar', lat:16.87, lng:96.2, capital:false, continent:'Azië'},
{name:'Kathmandu', country:'Nepal', lat:27.72, lng:85.32, capital:true, continent:'Azië'},
{name:'Pyongyang', country:'North Korea', lat:39.02, lng:125.75, capital:true, continent:'Azië'},
{name:'Muscat', country:'Oman', lat:23.61, lng:58.59, capital:true, continent:'Azië'},
{name:'Islamabad', country:'Pakistan', lat:33.68, lng:73.05, capital:true, continent:'Azië'},
{name:'Karachi', country:'Pakistan', lat:24.86, lng:67.01, capital:false, continent:'Azië'},
{name:'Ramallah', country:'Palestine', lat:31.9, lng:35.2, capital:true, continent:'Azië'},
{name:'Manila', country:'Philippines', lat:14.6, lng:120.98, capital:true, continent:'Azië'},
{name:'Doha', country:'Qatar', lat:25.29, lng:51.53, capital:true, continent:'Azië'},
{name:'Riyadh', country:'Saudi Arabia', lat:24.71, lng:46.68, capital:true, continent:'Azië'},
{name:'Jeddah', country:'Saudi Arabia', lat:21.49, lng:39.19, capital:false, continent:'Azië'},
{name:'Singapore', country:'Singapore', lat:1.35, lng:103.82, capital:true, continent:'Azië'},
{name:'Seoul', country:'South Korea', lat:37.57, lng:126.98, capital:true, continent:'Azië'},
{name:'Busan', country:'South Korea', lat:35.18, lng:129.08, capital:false, continent:'Azië'},
{name:'Colombo', country:'Sri Lanka', lat:6.93, lng:79.85, capital:true, continent:'Azië'},
{name:'Damascus', country:'Syria', lat:33.51, lng:36.29, capital:true, continent:'Azië'},
{name:'Taipei', country:'Taiwan', lat:25.03, lng:121.57, capital:true, continent:'Azië'},
{name:'Dushanbe', country:'Tajikistan', lat:38.56, lng:68.79, capital:true, continent:'Azië'},
{name:'Bangkok', country:'Thailand', lat:13.75, lng:100.5, capital:true, continent:'Azië'},
{name:'Dili', country:'Timor-Leste', lat:-8.56, lng:125.57, capital:true, continent:'Azië'},
{name:'Ankara', country:'Turkey', lat:39.93, lng:32.86, capital:true, continent:'Azië'},
{name:'Istanbul', country:'Turkey', lat:41.01, lng:28.98, capital:false, continent:'Azië'},
{name:'Ashgabat', country:'Turkmenistan', lat:37.95, lng:58.38, capital:true, continent:'Azië'},
{name:'Abu Dhabi', country:'United Arab Emirates', lat:24.45, lng:54.38, capital:true, continent:'Azië'},
{name:'Dubai', country:'United Arab Emirates', lat:25.2, lng:55.27, capital:false, continent:'Azië'},
{name:'Tashkent', country:'Uzbekistan', lat:41.3, lng:69.24, capital:true, continent:'Azië'},
{name:'Hanoi', country:'Vietnam', lat:21.03, lng:105.85, capital:true, continent:'Azië'},
{name:'Ho Chi Minh City', country:'Vietnam', lat:10.78, lng:106.7, capital:false, continent:'Azië'},
{name:'Sanaa', country:'Yemen', lat:15.37, lng:44.19, capital:true, continent:'Azië'},

/* ---------------- Afrika ---------------- */
{name:'Algiers', country:'Algeria', lat:36.75, lng:3.06, capital:true, continent:'Afrika'},
{name:'Luanda', country:'Angola', lat:-8.84, lng:13.23, capital:true, continent:'Afrika'},
{name:'Porto-Novo', country:'Benin', lat:6.5, lng:2.6, capital:true, continent:'Afrika'},
{name:'Gaborone', country:'Botswana', lat:-24.65, lng:25.91, capital:true, continent:'Afrika'},
{name:'Ouagadougou', country:'Burkina Faso', lat:12.37, lng:-1.53, capital:true, continent:'Afrika'},
{name:'Gitega', country:'Burundi', lat:-3.43, lng:29.93, capital:true, continent:'Afrika'},
{name:'Praia', country:'Cabo Verde', lat:14.93, lng:-23.51, capital:true, continent:'Afrika'},
{name:'Yaoundé', country:'Cameroon', lat:3.87, lng:11.52, capital:true, continent:'Afrika'},
{name:'Bangui', country:'Central African Republic', lat:4.37, lng:18.56, capital:true, continent:'Afrika'},
{name:'N\'Djamena', country:'Chad', lat:12.13, lng:15.06, capital:true, continent:'Afrika'},
{name:'Moroni', country:'Comoros', lat:-11.7, lng:43.26, capital:true, continent:'Afrika'},
{name:'Kinshasa', country:'Democratic Republic of the Congo', lat:-4.32, lng:15.31, capital:true, continent:'Afrika'},
{name:'Brazzaville', country:'Republic of Congo', lat:-4.27, lng:15.24, capital:true, continent:'Afrika'},
{name:'Yamoussoukro', country:'Ivory Coast', lat:6.83, lng:-5.29, capital:true, continent:'Afrika'},
{name:'Abidjan', country:'Ivory Coast', lat:5.36, lng:-4.01, capital:false, continent:'Afrika'},
{name:'Djibouti', country:'Djibouti', lat:11.59, lng:43.15, capital:true, continent:'Afrika'},
{name:'Cairo', country:'Egypt', lat:30.04, lng:31.24, capital:true, continent:'Afrika'},
{name:'Alexandria', country:'Egypt', lat:31.2, lng:29.92, capital:false, continent:'Afrika'},
{name:'Malabo', country:'Equatorial Guinea', lat:3.75, lng:8.78, capital:true, continent:'Afrika'},
{name:'Asmara', country:'Eritrea', lat:15.34, lng:38.93, capital:true, continent:'Afrika'},
{name:'Mbabane', country:'Eswatini', lat:-26.32, lng:31.14, capital:true, continent:'Afrika'},
{name:'Addis Ababa', country:'Ethiopia', lat:9.03, lng:38.74, capital:true, continent:'Afrika'},
{name:'Libreville', country:'Gabon', lat:0.42, lng:9.45, capital:true, continent:'Afrika'},
{name:'Banjul', country:'Gambia', lat:13.45, lng:-16.58, capital:true, continent:'Afrika'},
{name:'Accra', country:'Ghana', lat:5.6, lng:-0.19, capital:true, continent:'Afrika'},
{name:'Conakry', country:'Guinea', lat:9.64, lng:-13.58, capital:true, continent:'Afrika'},
{name:'Bissau', country:'Guinea-Bissau', lat:11.86, lng:-15.6, capital:true, continent:'Afrika'},
{name:'Nairobi', country:'Kenya', lat:-1.29, lng:36.82, capital:true, continent:'Afrika'},
{name:'Maseru', country:'Lesotho', lat:-29.31, lng:27.48, capital:true, continent:'Afrika'},
{name:'Monrovia', country:'Liberia', lat:6.31, lng:-10.8, capital:true, continent:'Afrika'},
{name:'Tripoli', country:'Libya', lat:32.89, lng:13.19, capital:true, continent:'Afrika'},
{name:'Antananarivo', country:'Madagascar', lat:-18.88, lng:47.5, capital:true, continent:'Afrika'},
{name:'Lilongwe', country:'Malawi', lat:-13.96, lng:33.79, capital:true, continent:'Afrika'},
{name:'Bamako', country:'Mali', lat:12.65, lng:-8.0, capital:true, continent:'Afrika'},
{name:'Nouakchott', country:'Mauritania', lat:18.09, lng:-15.98, capital:true, continent:'Afrika'},
{name:'Port Louis', country:'Mauritius', lat:-20.16, lng:57.5, capital:true, continent:'Afrika'},
{name:'Rabat', country:'Morocco', lat:34.02, lng:-6.83, capital:true, continent:'Afrika'},
{name:'Casablanca', country:'Morocco', lat:33.57, lng:-7.59, capital:false, continent:'Afrika'},
{name:'Maputo', country:'Mozambique', lat:-25.97, lng:32.57, capital:true, continent:'Afrika'},
{name:'Windhoek', country:'Namibia', lat:-22.56, lng:17.08, capital:true, continent:'Afrika'},
{name:'Niamey', country:'Niger', lat:13.51, lng:2.11, capital:true, continent:'Afrika'},
{name:'Abuja', country:'Nigeria', lat:9.08, lng:7.4, capital:true, continent:'Afrika'},
{name:'Lagos', country:'Nigeria', lat:6.52, lng:3.38, capital:false, continent:'Afrika'},
{name:'Kigali', country:'Rwanda', lat:-1.94, lng:30.06, capital:true, continent:'Afrika'},
{name:'São Tomé', country:'Sao Tome and Principe', lat:0.33, lng:6.73, capital:true, continent:'Afrika'},
{name:'Dakar', country:'Senegal', lat:14.72, lng:-17.47, capital:true, continent:'Afrika'},
{name:'Victoria', country:'Seychelles', lat:-4.62, lng:55.45, capital:true, continent:'Afrika'},
{name:'Freetown', country:'Sierra Leone', lat:8.48, lng:-13.23, capital:true, continent:'Afrika'},
{name:'Mogadishu', country:'Somalia', lat:2.05, lng:45.32, capital:true, continent:'Afrika'},
{name:'Pretoria', country:'South Africa', lat:-25.75, lng:28.19, capital:true, continent:'Afrika'},
{name:'Cape Town', country:'South Africa', lat:-33.92, lng:18.42, capital:false, continent:'Afrika'},
{name:'Johannesburg', country:'South Africa', lat:-26.2, lng:28.05, capital:false, continent:'Afrika'},
{name:'Juba', country:'South Sudan', lat:4.85, lng:31.6, capital:true, continent:'Afrika'},
{name:'Khartoum', country:'Sudan', lat:15.55, lng:32.53, capital:true, continent:'Afrika'},
{name:'Dodoma', country:'Tanzania', lat:-6.16, lng:35.75, capital:true, continent:'Afrika'},
{name:'Dar es Salaam', country:'Tanzania', lat:-6.79, lng:39.21, capital:false, continent:'Afrika'},
{name:'Lomé', country:'Togo', lat:6.13, lng:1.22, capital:true, continent:'Afrika'},
{name:'Tunis', country:'Tunisia', lat:36.81, lng:10.18, capital:true, continent:'Afrika'},
{name:'Kampala', country:'Uganda', lat:0.35, lng:32.58, capital:true, continent:'Afrika'},
{name:'Lusaka', country:'Zambia', lat:-15.39, lng:28.32, capital:true, continent:'Afrika'},
{name:'Harare', country:'Zimbabwe', lat:-17.83, lng:31.05, capital:true, continent:'Afrika'},
{name:'Hargeisa', country:'Somaliland', lat:9.56, lng:44.06, capital:false, continent:'Afrika'},
{name:'Laayoune', country:'Western Sahara', lat:27.15, lng:-13.2, capital:false, continent:'Afrika'},

/* ---------------- Noord-Amerika ---------------- */
{name:'Washington, D.C.', country:'United States of America', lat:38.9, lng:-77.04, capital:true, continent:'Noord-Amerika'},
{name:'New York City', country:'United States of America', lat:40.71, lng:-74.01, capital:false, continent:'Noord-Amerika'},
{name:'Los Angeles', country:'United States of America', lat:34.05, lng:-118.24, capital:false, continent:'Noord-Amerika'},
{name:'Chicago', country:'United States of America', lat:41.88, lng:-87.63, capital:false, continent:'Noord-Amerika'},
{name:'Ottawa', country:'Canada', lat:45.42, lng:-75.7, capital:true, continent:'Noord-Amerika'},
{name:'Toronto', country:'Canada', lat:43.65, lng:-79.38, capital:false, continent:'Noord-Amerika'},
{name:'Vancouver', country:'Canada', lat:49.28, lng:-123.12, capital:false, continent:'Noord-Amerika'},
{name:'Mexico City', country:'Mexico', lat:19.43, lng:-99.13, capital:true, continent:'Noord-Amerika'},
{name:'Guadalajara', country:'Mexico', lat:20.66, lng:-103.35, capital:false, continent:'Noord-Amerika'},
{name:'Guatemala City', country:'Guatemala', lat:14.63, lng:-90.51, capital:true, continent:'Noord-Amerika'},
{name:'Belmopan', country:'Belize', lat:17.25, lng:-88.77, capital:true, continent:'Noord-Amerika'},
{name:'San Salvador', country:'El Salvador', lat:13.69, lng:-89.22, capital:true, continent:'Noord-Amerika'},
{name:'Tegucigalpa', country:'Honduras', lat:14.1, lng:-87.22, capital:true, continent:'Noord-Amerika'},
{name:'Managua', country:'Nicaragua', lat:12.11, lng:-86.24, capital:true, continent:'Noord-Amerika'},
{name:'San José', country:'Costa Rica', lat:9.93, lng:-84.09, capital:true, continent:'Noord-Amerika'},
{name:'Panama City', country:'Panama', lat:8.98, lng:-79.52, capital:true, continent:'Noord-Amerika'},
{name:'Havana', country:'Cuba', lat:23.13, lng:-82.38, capital:true, continent:'Noord-Amerika'},
{name:'Kingston', country:'Jamaica', lat:17.97, lng:-76.79, capital:true, continent:'Noord-Amerika'},
{name:'Port-au-Prince', country:'Haiti', lat:18.59, lng:-72.31, capital:true, continent:'Noord-Amerika'},
{name:'Santo Domingo', country:'Dominican Republic', lat:18.49, lng:-69.94, capital:true, continent:'Noord-Amerika'},
{name:'Nassau', country:'Bahamas', lat:25.04, lng:-77.35, capital:true, continent:'Noord-Amerika'},
{name:'Bridgetown', country:'Barbados', lat:13.1, lng:-59.62, capital:true, continent:'Noord-Amerika'},
{name:'Port of Spain', country:'Trinidad and Tobago', lat:10.65, lng:-61.5, capital:true, continent:'Noord-Amerika'},
{name:'Saint John\'s', country:'Antigua and Barbuda', lat:17.12, lng:-61.85, capital:true, continent:'Noord-Amerika'},
{name:'Roseau', country:'Dominica', lat:15.3, lng:-61.39, capital:true, continent:'Noord-Amerika'},
{name:'Saint George\'s', country:'Grenada', lat:12.06, lng:-61.75, capital:true, continent:'Noord-Amerika'},
{name:'Basseterre', country:'Saint Kitts and Nevis', lat:17.3, lng:-62.72, capital:true, continent:'Noord-Amerika'},
{name:'Castries', country:'Saint Lucia', lat:14.0, lng:-61.0, capital:true, continent:'Noord-Amerika'},
{name:'Kingstown', country:'Saint Vincent and the Grenadines', lat:13.16, lng:-61.22, capital:true, continent:'Noord-Amerika'},

/* ---------------- Zuid-Amerika ---------------- */
{name:'Buenos Aires', country:'Argentina', lat:-34.6, lng:-58.38, capital:true, continent:'Zuid-Amerika'},
{name:'Sucre', country:'Bolivia', lat:-19.03, lng:-65.26, capital:true, continent:'Zuid-Amerika'},
{name:'La Paz', country:'Bolivia', lat:-16.5, lng:-68.15, capital:false, continent:'Zuid-Amerika'},
{name:'Brasília', country:'Brazil', lat:-15.79, lng:-47.88, capital:true, continent:'Zuid-Amerika'},
{name:'São Paulo', country:'Brazil', lat:-23.55, lng:-46.63, capital:false, continent:'Zuid-Amerika'},
{name:'Rio de Janeiro', country:'Brazil', lat:-22.91, lng:-43.17, capital:false, continent:'Zuid-Amerika'},
{name:'Santiago', country:'Chile', lat:-33.45, lng:-70.67, capital:true, continent:'Zuid-Amerika'},
{name:'Bogotá', country:'Colombia', lat:4.71, lng:-74.07, capital:true, continent:'Zuid-Amerika'},
{name:'Medellín', country:'Colombia', lat:6.24, lng:-75.58, capital:false, continent:'Zuid-Amerika'},
{name:'Quito', country:'Ecuador', lat:-0.18, lng:-78.47, capital:true, continent:'Zuid-Amerika'},
{name:'Georgetown', country:'Guyana', lat:6.8, lng:-58.16, capital:true, continent:'Zuid-Amerika'},
{name:'Asunción', country:'Paraguay', lat:-25.3, lng:-57.64, capital:true, continent:'Zuid-Amerika'},
{name:'Lima', country:'Peru', lat:-12.05, lng:-77.04, capital:true, continent:'Zuid-Amerika'},
{name:'Paramaribo', country:'Suriname', lat:5.87, lng:-55.17, capital:true, continent:'Zuid-Amerika'},
{name:'Montevideo', country:'Uruguay', lat:-34.9, lng:-56.16, capital:true, continent:'Zuid-Amerika'},
{name:'Caracas', country:'Venezuela', lat:10.49, lng:-66.88, capital:true, continent:'Zuid-Amerika'},

/* ---------------- Oceanië ---------------- */
{name:'Canberra', country:'Australia', lat:-35.28, lng:149.13, capital:true, continent:'Oceanië'},
{name:'Sydney', country:'Australia', lat:-33.87, lng:151.21, capital:false, continent:'Oceanië'},
{name:'Melbourne', country:'Australia', lat:-37.81, lng:144.96, capital:false, continent:'Oceanië'},
{name:'Wellington', country:'New Zealand', lat:-41.29, lng:174.78, capital:true, continent:'Oceanië'},
{name:'Auckland', country:'New Zealand', lat:-36.85, lng:174.76, capital:false, continent:'Oceanië'},
{name:'Suva', country:'Fiji', lat:-18.14, lng:178.44, capital:true, continent:'Oceanië'},
{name:'Port Moresby', country:'Papua New Guinea', lat:-9.44, lng:147.18, capital:true, continent:'Oceanië'},
{name:'Honiara', country:'Solomon Islands', lat:-9.43, lng:159.95, capital:true, continent:'Oceanië'},
{name:'Port Vila', country:'Vanuatu', lat:-17.73, lng:168.32, capital:true, continent:'Oceanië'},
{name:'Apia', country:'Samoa', lat:-13.83, lng:-171.76, capital:true, continent:'Oceanië'},
{name:'Nuku\'alofa', country:'Tonga', lat:-21.14, lng:-175.2, capital:true, continent:'Oceanië'},
{name:'Tarawa', country:'Kiribati', lat:1.33, lng:172.98, capital:true, continent:'Oceanië'},
{name:'Majuro', country:'Marshall Islands', lat:7.12, lng:171.19, capital:true, continent:'Oceanië'},
{name:'Palikir', country:'Micronesia', lat:6.92, lng:158.16, capital:true, continent:'Oceanië'},
{name:'Yaren', country:'Nauru', lat:-0.55, lng:166.92, capital:true, continent:'Oceanië'},
{name:'Ngerulmud', country:'Palau', lat:7.5, lng:134.62, capital:true, continent:'Oceanië'},
{name:'Funafuti', country:'Tuvalu', lat:-8.52, lng:179.2, capital:true, continent:'Oceanië'},

];
